### ISSUE TITLE
Add TODO list

### ISSUE THREAD

**Issue by chairco** [chairco/dj-realtime-visualization#1]
- [ ] Add API Authentication
- [ ] Add more views test
- [ ] Add API for get films data with time and return json format
